### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ShashwatPS**

### CODE REVIEW

**Comment by TanishBhole0911** [comment]
Change in Title for getting Started to 10

**Comment by Rakshit774** [comment]
hi

**Comment by Naman2005-create** [comment]
Naman Maheshwari

**Comment by shubhirusiya** [comment]
Hi I am Shubhi.

**Comment by agrawalha** [comment]
Harsh Agrawal

**Comment by navyasoni004** [comment]
HEYY..THIS IS NAVYA.

**Comment by roshani2510** [comment]
hi i am roshani

**Comment by adityasinghcode** [comment]
Aditya si ngh

**Comment by rajan570** [comment]
hey! i am rajan

**Pull request merged**
